yLevelAdjustment = true
allowUnderwater = false
windyDimensions = ["minecraft:overworld", "minecraft:the_end"]

[base]
strength = 0.4
strengthVariance = 0.15
gustFrequency = 0.1
modulationSpeed = 0.04
directionVariance = 0.002

[rain]
strength = 0.4
strengthVariance = 0.3
gustFrequency = 0.15
modulationSpeed = 0.04
directionVariance = 0.002

[storm]
strength = 3.2
strengthVariance = 0.3
gustFrequency = 0.2
modulationSpeed = 0.04
directionVariance = 0.002
