version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
oreganized = true
everycomp = true
arts_and_crafts = true
farmersdelight = true
darkerdepths = true
nomansland = true
wither_spawn_animation = true
puddleflood = true
dungeonsdelight = true
caverns_and_chasms = true
quark = true
another_furniture = true
sable_player_ragdoll = true
natures_spirit = true
modestmagic = true
diagonalwalls = true
wholecloth = true
sootychimneys = true
incision = true
newworld = true
appledog = true
amendments = true
buzzier_bees = true
frontiers = true
moonlight = true
diagonalfences = true
etcetera = true
alloyed = true
offroad = true
brick_and_mortar = true
enderscape = true
create_hypertube = true
supplementaries = true
glow = true
elysium_api = true
vista = true
suppsquared = true
clutternomore = true
sawmill = true
infernalexp = true
create = true
curiosities = true
aeronautics = true
bountifulfares = true
simulated = true
delicate_dyes = true
minecraft = true
the_beyond = true
firefly_bush_backport = true
bountifulpears = true
spawn = true
netherexp = true
bosses_of_mass_destruction = true
diagonalwindows = true
revotedwildfire = true
dynamicwaters = true
tolerable_creepers = true
